### PR TITLE
Improve developers' documentation

### PR DESCRIPTION
**Pull request by jowezarek**
**The first of potentially weekly(?) PRs improving Psydac's docstrings - any contribution is welcome @pyccel/psydac-dev !**

Files updated so far in this PR:

- `linalg.basic`

**Note:** I have started using :math:\`[insert standard latex code]\` in the docstrings of `linalg.basic` inspired by STRUPHY. Do we want to use this math-mode everywhere?

**To locally view your changes:**

- If not already done, now is a good time to create a venv
- If not already done: (let me know if these are not enough)
   - `sudo apt install graphviz` (Linux) or `brew install graphviz` (macOS)
   - `python -m pip install -r docs_requirements.txt`
- Go to `psydac/docs/`
- Execute `make html` *)
- Open the documentation on your browser with `open build/html/index.html`

*) While not necessary, instead of `make html` only, I like to execute 
- `rm -rf source/modules/STUBDIR`
- `make  clean`
- `make  html`
- `cd ..`
- `python docs/update_links.py` (this file cannot be executed from within `psydac/docs`)

### CODE REVIEW

**Comment by yguclu** [comment]
> **Note:** I have started using :math:`[insert standard latex code]` in the docstrings of `linalg.basic` inspired by STRUPHY. Do we want to use this math-mode everywhere?

I would prefer using the dollar sign `$` as a delimiter, as it minimizes the clutter in the docstrings (which is noticeable in inline mode). To this end the [sphinx-math-dollar](https://www.sympy.org/sphinx-math-dollar) extension could be used.

**Comment by jowezarek** [comment]
> > **Note:** I have started using :math:`[insert standard latex code]` in the docstrings of `linalg.basic` inspired by STRUPHY. Do we want to use this math-mode everywhere?
> 
> I would prefer using the dollar sign `$` as a delimiter, as it minimizes the clutter in the docstrings (which is noticeable in inline mode). To this end the [sphinx-math-dollar](https://www.sympy.org/sphinx-math-dollar) extension could be used.

77b099d9afd61099ee77ebaac728d9a80bae6fa1

I had to add 
```
from docutils.nodes import FixedTextElement, literal,math
from docutils.nodes import  comment, doctest_block, image, literal_block, math_block, paragraph, pending, raw, rubric, substitution_definition, target
math_dollar_node_blacklist = (literal,math,doctest_block, image, literal_block,  math_block,  pending,  raw,rubric, substitution_definition,target)
```
to the `conf.py`, as described in [https://github.com/sympy/sphinx-math-dollar/issues/18](url), because math mode in `autosummary` tables was not rendered properly using $ signs. This has not been an issue using `:math:`.

**Comment by yguclu** [comment]
@jowezarek Can you please add a few lines to our README file on how to build the documentation? Alternatively we can put the instructions directly in the developers' documentation (https://pyccel.github.io/psydac/), as I do not expect the library users to build the documentation locally.

**Comment by jowezarek** [comment]
> @jowezarek Can you please add a few lines to our README file on how to build the documentation? Alternatively we can put the instructions directly in the developers' documentation (https://pyccel.github.io/psydac/), as I do not expect the library users to build the documentation locally.

5736b6f180225fac3db4f94694dfb792e7000cc9

**Review by yguclu — APPROVED** [review]
Good job!

**Pull request merged**
