### PR TITLE
Fix warnings in the tests

### LINKED ISSUE #268: Future pytest problem
Pytest is raising lots of warnings in the tests. Collecting warnings can be quite slow so this will be slowing down the tests.

Example:
```python
polar/tests/test_c1_linops.py::test_c1_linops[pads0-npts0-2]
  /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/_pytest/python.py:199: PytestReturnNotNoneWarning: Expected None, but polar/tests/test_c1_linops.py::test_c1_linops[pads0-npts0-2] returned {'n0': 2, 'npts': [5, 8], 'pads': (2, 3), 'verbose': False, 'n1': 7, 'n2': 8, 'p1': 2, 'p2': 3, 'P1': False, 'P2': True, 'nc1': 5, 'nc2': 8, 'U': <psydac.polar.dense.DenseVectorSpace object at 0x7fc707a501c0>, 'domain_decomposition': <psydac.ddm.cart.DomainDecomposition object at 0x7fc707a50250>, 'global_starts': [array([0]), array([0])], 'global_ends': [array([4]), array([7])], 'axis': 1, 'es': array([0]), 'ee': array([7]), 'cart': <psydac.ddm.cart.CartDecomposition object at 0x7fc707a502e0>, 'V': <psydac.linalg.stencil.StencilVectorSpace object at 0x7fc707a501f0>, 'W': <psydac.linalg.block.BlockVectorSpace object at 0x7fc707a502b0>, 's1': 0, 's2': 0, 'e1': 4, 'e2': 7, 'Aa': array([[0.713, 0.813],
         [0.327, 0.22 ]]), 'Ba': array([[[0.327, 0.964, 0.096, 0.162, 0.694, 0.14 , 0.267, 0.803, 0.301, 0.597, 0.573, 0.265, 0.249, 0.29 ],
          [0.876, 0.019, 0.092, 0.341, 0.22 , 0.563, 0.539, 0.495, 0.301, 0.511, 0.786, 0.813, 0.533, 0.806]],
  
         [[0.034, 0.154, 0.748, 0.385, 0.318, 0.572, 0.372, 0.91 , 0.387, 0.836, 0.602, 0.912, 0.484, 0.959],
          [0.577, 0.028, 0.739, 0.861, 0.099, 0.963, 0.563, 0.741, 0.224, 0.941, 0.643, 0.543, 0.961, 0.557]]]), 'Ca': array([[[0.532, 0.045],
          [0.546, 0.744],
          [0.368, 0.679],
          [0.564, 0.208],
          [0.547, 0.476],
          [0.338, 0.663],
          [0.061, 0.373],
          [0.434, 0.974]],
  
         [[0.698, 0.626],
          [0.156, 0.435],
          [0.371, 0.94 ],
          [0.453, 0.855],
          [0.654, 0.879],
          [0.003, 0.925],
          [0.951, 0.155],
          [0.066, 0.317]]]), 'A': <psydac.polar.dense.DenseMatrix object at 0x7fc707a50340>, 'B': <psydac.polar.c1_linops.LinearOperator_StencilToDense object at 0x7fc707a50430>, 'C': <psydac.polar.c1_linops.LinearOperator_DenseToStencil object at 0x7fc707a50490>, 'D': <psydac.linalg.stencil.StencilMatrix object at 0x7fc707a504f0>, 'M': <psydac.linalg.block.BlockMatrix object at 0x7fc707a50550>, 'u': <psydac.polar.dense.DenseVector object at 0x7fc707a50520>, 'v': <psydac.linalg.stencil.StencilVector object at 0x7fc707a505b0>, 'w': <psydac.linalg.block.BlockVector object at 0x7fc707a50610>, 'x': <psydac.linalg.block.BlockVector object at 0x7fc707a50640>, 'x0': <psydac.polar.dense.DenseVector object at 0x7fc707a507c0>, 'x1': <psydac.linalg.stencil.StencilVector object at 0x7fc707a50730>, 'tols': {'rtol': 1e-12, 'atol': 1e-12}, '@py_assert1': None, '@py_assert3': None, '@py_assert5': None, '@py_assert7': None, '@py_assert10': None, '@py_assert12': None, '@py_assert15': None, 'Ma': array([[0.713, 0.813, 0.428, ..., 0.   , 0.   , 0.   ],
         [0.327, 0.22 , 1.297, ..., 0.   , 0.   , 0.   ],
         [0.532, 0.045, 0.541, ..., 0.   , 0.   , 0.   ],
         ...,
         [0.   , 0.   , 0.   , ..., 0.303, 0.432, 0.477],
         [0.   , 0.   , 0.   , ..., 0.547, 0.635, 0.476],
         [0.   , 0.   , 0.   , ..., 0.058, 0.965, 0.494]]), 'wa': array([0.   , 1.   , 0.273, 0.675, 0.356, 0.922, 0.373, 0.964, 0.187, 0.468, 0.527, 0.574, 0.399, 0.539, 0.238, 0.253, 0.076, 0.541, 0.489, 0.968, 0.786, 0.694, 0.285, 0.224, 0.691, 0.222, 0.074,
         0.333, 0.551, 0.2  , 0.112, 0.865, 0.458, 0.004, 0.248, 0.045, 0.255, 0.425, 0.144, 0.937, 0.462, 0.86 ]), 'xa': array([6.283, 7.024, 6.028, 4.871, 5.918, 5.057, 5.728, 5.562, 4.746, 6.18 , 8.548, 5.611, 7.23 , 5.951, 9.08 , 7.193, 6.021, 5.638, 8.594, 6.505, 7.282, 8.045, 6.458, 7.789, 8.007, 6.587, 5.928,
         4.911, 5.636, 5.316, 7.037, 5.443, 5.007, 5.569, 4.103, 4.804, 4.03 , 5.072, 4.738, 4.755, 3.103, 4.085]), '@py_assert8': None, '@py_assert11': None}, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
```

The problem is even worse if we read the contents of the warning:

> polar/tests/test_c1_linops.py::test_c1_linops[pads0-npts0-2]
>   /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/_pytest/python.py:199: PytestReturnNotNoneWarning: Expected None, but polar/tests/test_c1_linops.py::test_c1_linops[pads0-npts0-2] returned {...}, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?

as this will apparently become an error in a future pytest version

### PR DESCRIPTION
**Pull request by tomcaruso**
Make test functions return their `locals()` dictionary only if the `verbose` flag is set to `True`. This fixes #268: Pytest does not raise warning messages which will be become errors in a future version.

### CODE REVIEW

**Review by yguclu — COMMENTED** [review]
As far as I can tell Pytest only complains about the test functions (whose name starts with `test_`), which should always return `None`. This happens only for `polar/tests/test_c1_linops.py::test_c1_linops`. I do not understand why you modified other functions which do not cause any warnings.

**Comment by tomcaruso** [comment]
You are right. I had assumed that the problem was with all functions that returned locals(). 

I don't think the other functions need to be changed. Or maybe it would improve the speed of the algorithm not to return locals()? So we could improve the speed of the test. 

If you don't think so, we could just remove the change in these functions.

**Comment by yguclu** [comment]
I do not think that local functions returning `locals` cause a slow down in the tests, since the dictionary is only passed by reference (no copy is made). The one side effect of returning `locals` is that objects created in the function cannot be deallocated upon local function exit; instead they will persist in memory a bit longer, until the calling test function exits.

Feel free to check the run time of the tests before and after your changes. If you do not see significant changes, I suggest that you roll back any change that was not strictly required.

**Comment by tomcaruso** [comment]
You were right. In fact, it's even a little faster if we return locals().

**Review by yguclu — APPROVED** [review]

**Pull request merged**
